### ISSUE TITLE
BorrowMutError in svgdom::dom::node_data::NodeData::detach

### ISSUE THREAD

**Issue by i80and** [RazrFalcon/svgcleaner#131]
## Summary

When running `svgcleaner` on https://github.com/mongodb/docs/blob/master/source/images/crud-write-concern-ack.svg I get the error `thread 'main' panicked at 'already borrowed: BorrowMutError'`.

Compiled with `1.25.0-nightly (3bd4af88b 2018-01-18)`, running on macOS.

## Backtrace

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001003602f4 svgcleaner`rust_panic at panicking.rs:607 [opt]
    frame #1: 0x00000001003602d1 svgcleaner`std::panicking::rust_panic_with_hook::h407d06fffbe934da at panicking.rs:592 [opt]
    frame #2: 0x000000010036008f svgcleaner`std::panicking::begin_panic::h920e256577b254d6 at panicking.rs:537 [opt]
    frame #3: 0x000000010035ffe4 svgcleaner`std::panicking::begin_panic_fmt::h90b1bd692861f55b at panicking.rs:521 [opt]
    frame #4: 0x000000010035ff53 svgcleaner`rust_begin_unwind at panicking.rs:497 [opt]
    frame #5: 0x00000001003a9b14 svgcleaner`core::panicking::panic_fmt::h76c861a27b074664 at panicking.rs:71 [opt]
    frame #6: 0x00000001001205cc svgcleaner`core::result::unwrap_failed::hd423a511358a3292(msg="already borrowed", error=BorrowMutError @ 0x00007ffeefbfd1d8) at macros.rs:23
    frame #7: 0x000000010011e435 svgcleaner`_$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::expect::h62234484151f64ea(self=Err, msg="already borrowed") at result.rs:809
    frame #8: 0x0000000100135276 svgcleaner`_$LT$core..cell..RefCell$LT$T$GT$$GT$::borrow_mut::h3fe80e65e064f2a8(self=&0x101a8f0f0) at cell.rs:772
    frame #9: 0x00000001000fcf75 svgcleaner`svgdom::dom::node_data::NodeData::detach::h64c7faa3e250c15a(self=&0x101a928f8) at node_data.rs:54
    frame #10: 0x00000001000f7274 svgcleaner`svgdom::dom::node::Node::prepend::haf9354a805eaf71c(self=&0x7ffeefbfd898, new_child=&0x7ffeefbfd8a0) at node.rs:446
    frame #11: 0x0000000100083c29 svgcleaner`svgcleaner::task::group_defs::group_defs::hb0a3786d78cb227e(doc=&0x7ffeefbff160) at group_defs.rs:40
    frame #12: 0x00000001000ea122 svgcleaner`svgcleaner::cleaner::clean_doc::h16f5cc13b26f9d3f(doc=&0x7ffeefbff160, options=&0x7ffeefbfeea0, opt=&0x7ffeefbfee90) at cleaner.rs:82
    frame #13: 0x000000010000bff0 svgcleaner`svgcleaner::main::h43e3e81b12b3afc3 at main.rs:137
    frame #14: 0x00000001000124e2 svgcleaner`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h6e0a4f1a17f45c42 at rt.rs:74
    frame #15: 0x000000010035feb8 svgcleaner`std::panicking::try::do_call::hcc5a1dc1920122fa [inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h99a58e47456913c4 at rt.rs:59 [opt]
    frame #16: 0x000000010035feac svgcleaner`std::panicking::try::do_call::hcc5a1dc1920122fa at panicking.rs:479 [opt]
    frame #17: 0x0000000100379e5f svgcleaner`__rust_maybe_catch_panic at lib.rs:102 [opt]
    frame #18: 0x000000010036ae0d svgcleaner`std::rt::lang_start_internal::h3dc73f619774ac33 [inlined] std::panicking::try::h48548b136d551c0f at panicking.rs:458 [opt]
    frame #19: 0x000000010036adda svgcleaner`std::rt::lang_start_internal::h3dc73f619774ac33 [inlined] std::panic::catch_unwind::ha9118c34cdd2c6d7 at panic.rs:358 [opt]
    frame #20: 0x000000010036adda svgcleaner`std::rt::lang_start_internal::h3dc73f619774ac33 at rt.rs:58 [opt]
    frame #21: 0x00000001000124c2 svgcleaner`std::rt::lang_start::h6ae2b9a5b0d77f01(main=&0x10000a760, argc=4, argv=&0x7ffeefbff798) at rt.rs:74
    frame #22: 0x000000010000c475 svgcleaner`main + 37
    frame #23: 0x00007fff75de4115 libdyld.dylib`start + 1
    frame #24: 0x00007fff75de4115 libdyld.dylib`start + 1
```

**Comment by i80and** [comment]
Thank you very much!
